### PR TITLE
New compiler versions for GCC, Clang & Apple-Clang

### PR DESCRIPTION
**Pull request by helmesjo**
GCC 8
Clang 6.0
Apple-clang 9.1

### CODE REVIEW

**Comment by helmesjo** [comment]
@lasote All green with the added compilers.

**Comment by helmesjo** [comment]
@lasote I'm seeing `Upload skipped, credentials for remote 'upload_repo' not available` for all of the builds. Missing the `CONAN_PASSWORD` envar?

**Comment by lasote** [comment]
weird, the CONAN_PASSWORD is set...

**Comment by lasote** [comment]
Ah! I think the builds we were looking belong to the PR, this one is the good one, unfortunately a Boost build is in progress so will take some time to start: https://travis-ci.org/conan-community/conan-openssl/builds/416311420

**Comment by helmesjo** [comment]
Oh, haha! My bad! 🥇

**Comment by helmesjo** [comment]
@lasote Build [1.0.50](https://ci.appveyor.com/project/lasote/conan-openssl-stnt8/build/1.0.50) appears to have failed on appveyor (connection issue).
Could you restart it?

**Comment by lasote** [comment]
Launched! many thanks.

**Pull request merged**
