### PR TITLE
Avoid creating versioned libraries for Android

### PR DESCRIPTION
**Pull request by raffienficiaud**
On Android, having versioned libraries with the symlink pointing to the shared
library may not work at packaging time: the real library may be discarded and
only the symlink may appear in the final apk.

This patch avoid creating the versioned library. Tested on Android and 1.0.2p + 1.0.2o.

Let me know if this is something you would like to have in an old release branch.

NB: I tried to port the changes to the `1.1.1` series but I am not able to compile for Android
right now and I may need support.

### CODE REVIEW

**Comment by raffienficiaud** [comment]
Tested also with `1.0.2q`.

**Comment by raffienficiaud** [comment]
Dear @SSE4 

I see the PR as closed, what is the status on the merge itself?

**Comment by SSE4** [comment]
I will take a look and create newer PR. recipe has changed significantly, so it needs to be re-done.

**Comment by raffienficiaud** [comment]
Thanks for the reply. So if you say it should be applied on latest master, I can change the proposed PR and adapt it.

**Comment by SSE4** [comment]
yeah. please also check, if it's possible to achieve without a patching of makefiles, may be there is a corresponding configuration option available already?

**Comment by raffienficiaud** [comment]
Ok, will give a try and keep you posted.

**Comment by SSE4** [comment]
also, check this out: https://github.com/openssl/openssl/issues/3902

**Comment by raffienficiaud** [comment]
Yes I checked this but this was not doing the job as expected. I will give another shot.

**Pull request closed without merging**
