### PR TITLE
Fix Travis builds

### PR DESCRIPTION
**Pull request by uilianries**
/cc @Croydon 

We can ignore Azure. It's not possible ignoring Azure only, it requires [skip ci] which will affect all 3 services.

### CODE REVIEW

**Comment by Croydon** [comment]
Homebrew had a timeout

**Comment by uilianries** [comment]
> Homebrew had a timeout
> 
> [travis-ci.org/conan-community/conan-openssl/jobs/562255787](https://travis-ci.org/conan-community/conan-openssl/jobs/562255787)

restarted

**Comment by uilianries** [comment]
Why is circle ci not listed? :thinking:

**Comment by Croydon** [comment]
Maybe it is only enabled for pushes not pull requests?

**Comment by uilianries** [comment]
> Maybe it is only enabled for pushes not pull requests?

Yes, I think so.

**Comment by uilianries** [comment]
I canceled Azure and Circle CI. This PR is only related to Travis.

**Comment by uilianries** [comment]
I just removed stages from Travis file. That feature help us to organize our build, but at same it increases our CI time in hours.

**Pull request merged**
