### PR TITLE
- general recipe rewrite:

### PR DESCRIPTION
**Pull request by SSE4**
* single recipe works for 1.0.2x, 1.1.0x and 1.1.1x
* for 1.1.0x and 1.1.1x recipe uses OpenSSL targets
* supported platforms are extracted to the single place
* install is used to package files
* generic clean up

Signed-off-by: SSE4 <tomskside@gmail.com>

### CODE REVIEW

**Comment by uilianries** [comment]
@SSE4 we need to remove OpenSSL from Appyeor after accepting this PR

**Comment by uilianries** [comment]
Touché! It looks like be storage problem.

From https://dev.azure.com/conan-community/packages/_build/results?buildId=12

OpenSSL_1_1_0k_VS2015 Visual Studio 14:

I putted fsutil to scan free space when calling build():

free space on 1st build: 3.48 GB
free space on 2nd build: 2.66 GB
free space on 3rd build: 1.83 GB
free space on 4th build: 1.68 GB
free space on 5th build: 1.02 GB
free space on 6th build: 0.38 GB
free space on 7th build: 0.21 GB

Ops!

I'll add more pages to increase the storage size

**Comment by SSE4** [comment]
great!

**Comment by uilianries** [comment]
Even splitting in more pages, it's not enough ...

https://dev.azure.com/uilianr/conan-devops/_build/results?buildId=303

Azure offers 10GB in total:

https://developercommunity.visualstudio.com/content/problem/566745/build-machine-running-out-of-disk-space.html
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&viewFallbackFrom=vsts

My idea: remove cached packages after uploading.

**Comment by uilianries** [comment]
I've added Conan hooks to remove all cache after each package build. It worked on my CI jobs. Let's see here.

**Pull request merged**
