### PR TITLE
1.1.1

### PR DESCRIPTION
**Pull request by Y0UZ45**
## Changes
- Update OpenSSL to 1.1.1
- Replace `md5.cpp` with `digest.cpp`
- Add `SHA1`, `SHA2` and `SHA3` tests

### CODE REVIEW

**Comment by SSE4** [comment]
OSX builds failed, I'll take a look

**Comment by lasote** [comment]
Visual still failing due duplicated symbols error, please @SSE4 take a look

**Comment by SSE4** [comment]
it seems to be picking up OpenSSL installed on appveyor, `"C:\OpenSSL-Win32\lib\VC\ssleay32MDd.lib" "C:\OpenSSL-Win32\lib\VC\libeay32MDd.lib"`, I'll try to figure out how to disable it

**Comment by Croydon** [comment]
Can the default branch be updated to 1.1.1?

**Comment by SSE4** [comment]
@Croydon done (please NOTE builds are still running)

**Pull request merged**
